/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Alert
         * @description An unresolved issue flagged by the alert service for a property manager.
         */
        Alert: {
            /** Id */
            id: string;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /** Property Id */
            property_id: string;
            /** Property Name */
            property_name: string;
            /** Type */
            type: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Message */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Dismissed
             * @default false
             */
            dismissed: boolean;
        };
        /** AssignRoomPayload */
        AssignRoomPayload: {
            /** Room Id */
            room_id: string | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["ChatMessage"][];
        };
        /** ControlPayload */
        ControlPayload: {
            /** Command */
            command: string;
            /** Value */
            value?: unknown;
        };
        /**
         * DeleteResult
         * @description Confirmation that a device was removed from the registry.
         */
        DeleteResult: {
            /** Deleted */
            deleted: string;
        };
        /**
         * DeviceCommandResult
         * @description Outcome of a turn_on / turn_off command.
         */
        DeviceCommandResult: {
            /** Success */
            success: boolean;
            /** State */
            state: boolean;
        };
        /**
         * DeviceResponse
         * @description The flat device shape the list/get endpoints return (``SpireDevice.to_api()``).
         *
         *     This is the typed contract the frontend consumes — and what the generated
         *     cross-language types in ``shared/`` are produced from.
         */
        DeviceResponse: {
            /** Id */
            id: string;
            /** Vendor Id */
            vendor_id: string;
            /** Vendor */
            vendor: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Online */
            online: boolean;
            /** Controllable */
            controllable: boolean;
            /** State */
            state: {
                [key: string]: unknown;
            };
            /** Power Draw */
            power_draw?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Humidity */
            humidity?: number | null;
            /** Leak Detected */
            leak_detected?: boolean | null;
            /** Property Id */
            property_id?: string | null;
            /** Room Id */
            room_id?: string | null;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Supported Commands */
            supported_commands: string[];
            /** Traits */
            traits: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Insight
         * @description Claude-generated insight for a single device, cached in Upstash Redis.
         */
        Insight: {
            /** Device Id */
            device_id: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @default info
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /**
             * Model Used
             * @default
             */
            model_used: string;
        };
        /** IntelligenceItem */
        IntelligenceItem: {
            /** Id */
            id: string;
            /** Property Id */
            property_id: string;
            /** Property Name */
            property_name: string;
            /** Type */
            type: string;
            /** Severity */
            severity: string;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Generated At */
            generated_at: string;
            /** Metric */
            metric?: number | null;
            /** Unit */
            unit?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MatterCommandPayload */
        MatterCommandPayload: {
            /** Command */
            command: string;
            /** Value */
            value?: unknown;
        };
        /** MatterCommissionPayload */
        MatterCommissionPayload: {
            /** Setup Code */
            setup_code: string;
            /**
             * Property Id
             * @default
             */
            property_id: string;
            /**
             * Room Id
             * @default
             */
            room_id: string;
        };
        /**
         * MatterDeviceState
         * @description Live attribute snapshot for a Matter device.
         */
        MatterDeviceState: {
            /** Device Id */
            device_id: string;
            /** Node Id */
            node_id: string;
            /** Online */
            online: boolean;
            /** On Off */
            on_off?: boolean | null;
            /** Brightness */
            brightness?: number | null;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            organization?: components["schemas"]["OrganizationOut"] | null;
        };
        /** OrganizationOut */
        OrganizationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * Property
         * @description A property managed by an organisation on the Alphacon platform.
         */
        Property: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Organisation Id */
            organisation_id?: string | null;
            /**
             * Device Count
             * @default 0
             */
            device_count: number;
            /**
             * Alert Count
             * @default 0
             */
            alert_count: number;
            /**
             * Status
             * @default all_clear
             * @enum {string}
             */
            status: "all_clear" | "needs_attention" | "critical";
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
        };
        /** ProvisionPayload */
        ProvisionPayload: {
            /** Hotspot Name */
            hotspot_name: string;
            /** Wifi Ssid */
            wifi_ssid: string;
            /** Wifi Password */
            wifi_password: string;
            /**
             * Property Id
             * @default
             */
            property_id: string;
            /**
             * Room Id
             * @default
             */
            room_id: string;
        };
        /** RenamePayload */
        RenamePayload: {
            /** Name */
            name: string;
        };
        /** Room */
        Room: {
            /** Id */
            id?: string;
            /** Property Id */
            property_id: string;
            /** Name */
            name: string;
            /** Floor */
            floor?: number | null;
            /**
             * Device Count
             * @default 0
             */
            device_count: number;
            /**
             * Alert Count
             * @default 0
             */
            alert_count: number;
        };
        /** RoomCreate */
        RoomCreate: {
            /** Name */
            name: string;
            /** Floor */
            floor?: number | null;
        };
        /** SaveDevicePayload */
        SaveDevicePayload: {
            /** Vendor */
            vendor: string;
            /** Name */
            name: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Ip
             * @default
             */
            ip: string;
            /**
             * Mac
             * @default
             */
            mac: string;
            /**
             * Property Id
             * @default
             */
            property_id: string;
            /** Room Id */
            room_id?: string | null;
            /**
             * Vendor Id
             * @default
             */
            vendor_id: string;
        };
        /** ShellyScanPayload */
        ShellyScanPayload: {
            /** Hotspot Name */
            hotspot_name: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Organization Name */
            organization_name?: string | null;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Status */
            status: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
